repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
        exclude: \.json$
      - id: end-of-file-fixer
        exclude: \.json$
